---
abstract: 'Windows file functions that use very long paths and Unicode.'
author:
  - 'Robert Boisvert <rdbprog@gmail.com>'
build_requires:
  Devel::PPPort: 3.19
  Devel::Refcount: 0
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.36
  ExtUtils::ParseXS: 3.18
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Win32-LongPath
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Encode: 0
  Fcntl: 0
  File::Spec::Functions: 0
  Time::Local: 0
  XSLoader: 0.02
resources:
  bugtracker: https://github.com/rdboisvert/Win32-LongPath/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/rdboisvert/Win32-LongPath
